---
- name: Import AAP orgs
  hosts: localhost
  gather_facts: no

  tasks:
  - name: Read organisations file
    include_vars:
      file: organisations.yaml

  - name: Create organization
    awx.awx.organization:
      name: "{{ item }}"
      description: "{{ item }} bar organization"
      state: present
      controller_username: "admin"
      controller_password: "redhat"
      controller_host: "192.168.1.21"
      validate_certs: false

    with_items: "{{ organisations }}"